"""Provider-neutral queue protocol."""

from typing import Protocol

from footballai_v2.execution.contracts import ExecutionJob
from footballai_v2.storage.ports import AnalysisRepository


class JobQueue(Protocol):
    def enqueue(self, job: ExecutionJob) -> None: ...
    def claim(self, worker_id: str) -> ExecutionJob | None: ...
    def complete(self, job: ExecutionJob) -> None: ...
    def fail(self, job: ExecutionJob) -> None: ...
    def cancel(self, run_id: str) -> bool: ...
    def recover_abandoned(self, timeout_seconds: float, store: AnalysisRepository) -> int: ...
