"""Split control-plane / data-plane end-to-end acceptance.

This is the headline P2.5 proof: the *real* AnalysisCoordinator, AnalysisExecutor
and API read path drive a full analysis through three independent providers --
PostgreSQL (control plane), Azure Blob via Azurite (data plane), and the local
filesystem queue (delivery) -- with no shared filesystem between the ingesting
"API" side and the executing "worker" side.

Runs only when both emulators are configured (``FOOTBALLAI_TEST_DATABASE_URL`` and
``FOOTBALLAI_TEST_BLOB_CONNECTION_STRING``); otherwise the whole module is
skipped so the fast deterministic suite never needs Docker. It uses tiny
generated byte payloads and the deterministic ``demo_fast`` / ``test_fail``
profiles -- never a real video or model.
"""

from __future__ import annotations

import io
import os
import uuid

import pytest

pytest.importorskip("sqlalchemy")
pytest.importorskip("azure.storage.blob")

from sqlalchemy import create_engine, text  # noqa: E402

from footballai_v2.api import create_app  # noqa: E402
from footballai_v2.api.legacy_adapter import LegacyRunAdapter  # noqa: E402
from footballai_v2.contracts.v1 import AnalysisRunStatus, DataOrigin  # noqa: E402
from footballai_v2.execution.coordinator import AnalysisCoordinator, ExecutionSettings  # noqa: E402
from footballai_v2.execution.executor import AnalysisExecutor  # noqa: E402
from footballai_v2.execution.queue.local_filesystem import LocalFilesystemQueue  # noqa: E402
from footballai_v2.storage.object_storage.azure_blob import AzureBlobObjectStorage  # noqa: E402
from footballai_v2.storage.object_storage.credentials import (  # noqa: E402
    ConnectionStringCredential,
    _parse_connection_string,
)
from footballai_v2.storage.postgres import PostgreSQLAnalysisRepository  # noqa: E402

_DATABASE_URL = os.getenv("FOOTBALLAI_TEST_DATABASE_URL")
_BLOB_CONNECTION = os.getenv("FOOTBALLAI_TEST_BLOB_CONNECTION_STRING")
_TABLES = (
    "audit_events",
    "artifact_metadata",
    "stage_executions",
    "analysis_attempts",
    "logical_analyses",
)

pytestmark = pytest.mark.skipif(
    not (_DATABASE_URL and _BLOB_CONNECTION),
    reason="set FOOTBALLAI_TEST_DATABASE_URL and FOOTBALLAI_TEST_BLOB_CONNECTION_STRING "
    "(PostgreSQL + Azurite) to run the split-plane E2E",
)

VIDEO = b"bounded-generated-video-bytes"


@pytest.fixture(scope="session")
def _migrated_url() -> str:
    from alembic import command
    from alembic.config import Config

    migrations_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "migrations")
    os.environ["FOOTBALLAI_DATABASE_URL"] = _DATABASE_URL
    cfg = Config()
    cfg.set_main_option("script_location", migrations_dir)
    command.upgrade(cfg, "head")
    return _DATABASE_URL


@pytest.fixture(scope="session")
def _engine(_migrated_url):
    engine = create_engine(_migrated_url, future=True)
    yield engine
    engine.dispose()


@pytest.fixture
def _clean(_engine):
    with _engine.begin() as connection:
        connection.execute(text(f"TRUNCATE {', '.join(_TABLES)} CASCADE"))
    return _engine


@pytest.fixture
def object_storage() -> AzureBlobObjectStorage:
    # A fresh private container per test isolates blob state without a truncate.
    fields = _parse_connection_string(_BLOB_CONNECTION)
    credential = ConnectionStringCredential(
        connection_string=_BLOB_CONNECTION,
        container=f"e2e-{uuid.uuid4().hex[:16]}",
        account_name=fields["AccountName"],
        account_key=fields["AccountKey"],
    )
    return AzureBlobObjectStorage(credential)


@pytest.fixture
def split(tmp_path, _clean, object_storage, monkeypatch):
    """A coordinator + executor wired to PostgreSQL + Blob + local queue."""
    # Declared backends make ExecutionSettings validate the split configuration
    # honestly; the actual behaviour comes from the injected ports below.
    monkeypatch.setenv("FOOTBALLAI_DATABASE_URL", _DATABASE_URL)
    monkeypatch.setenv("FOOTBALLAI_BLOB_CONNECTION_STRING", _BLOB_CONNECTION)
    monkeypatch.setenv("FOOTBALLAI_BLOB_CONTAINER", object_storage._container)
    settings = ExecutionSettings(
        tmp_path / "runs",
        tmp_path / "queue",
        max_upload_bytes=1024 * 1024,
        allow_test_profiles=True,
        environment="test",
        database_backend="postgres",
        object_storage_backend="azure_blob",
        queue_backend="local",
    )
    # ffprobe is not meaningful for a byte payload; the probe is validated
    # elsewhere. Everything else in the ingestion path is exercised for real.
    monkeypatch.setattr(
        AnalysisCoordinator,
        "probe_video",
        lambda self, path, extension: {"duration_seconds": 60.0, "container": "mp4", "size_bytes": path.stat().st_size},
    )
    repository = PostgreSQLAnalysisRepository(_clean, verify_schema=True)
    queue = LocalFilesystemQueue(settings.queue_root)
    coordinator = AnalysisCoordinator(
        settings, repository=repository, object_storage=object_storage, queue=queue
    )
    executor = AnalysisExecutor(repository, object_storage, stage_delay_seconds=0)
    return coordinator, executor, settings


def _ingest(coordinator, *, profile="demo_fast", content=VIDEO):
    import hashlib

    temporary, checksum, size, extension = coordinator.stream_upload(io.BytesIO(content), "match.mp4")
    assert checksum == hashlib.sha256(content).hexdigest()
    return coordinator.create_analysis(
        temporary,
        filename="match.mp4",
        checksum=checksum,
        size_bytes=size,
        extension=extension,
        content_type="video/mp4",
        metadata={"match_name": "Split Plane Derby", "pipeline_profile": profile, "data_origin": "evaluation"},
    )


def test_demo_fast_runs_through_postgres_blob_and_queue(split):
    coordinator, executor, settings = split

    # 1. Ingest through the real coordinator: attempt -> PostgreSQL, bytes -> Blob.
    run = _ingest(coordinator)
    assert run.status is AnalysisRunStatus.QUEUED

    # 2. The attempt exists in the PostgreSQL control plane.
    assert coordinator.repository.load(run.run_id).run_id == run.run_id

    # 3. The source bytes live in object storage (Azurite), not on any API disk.
    assert coordinator.object_storage.has_input(run.run_id) is True
    with coordinator.object_storage.materialize_input(run.run_id) as materialized:
        assert materialized.read_bytes() == VIDEO

    # 4. The queue delivered exactly the stable run identity.
    job = coordinator.queue.claim("e2e-worker")
    assert job is not None and job.run_id == run.run_id

    # 5. The real executor materializes input from Blob, runs demo_fast, and
    #    publishes artifacts to Blob with metadata to PostgreSQL.
    status = executor.execute(job, "e2e-worker")
    assert status is AnalysisRunStatus.SUCCEEDED

    completed = coordinator.repository.load(run.run_id)
    assert completed.status is AnalysisRunStatus.SUCCEEDED
    assert completed.artifacts, "artifact metadata must be recorded in PostgreSQL"

    # 6. Artifact bytes are readable from Blob and pass integrity.
    summary = coordinator.object_storage.read_artifact_bytes(run.run_id, "team-summary")
    assert b"footballai.team-summary/v1" in summary
    for artifact in completed.artifacts:
        assert coordinator.object_storage.artifact_integrity(run.run_id, artifact.artifact_id)

    # 7. The API read path serves results through the same ports (split mode),
    #    proving the API needs no shared filesystem with the worker.
    client = create_app(settings.run_root, settings=settings)
    from fastapi.testclient import TestClient

    with TestClient(client) as http:
        # Readiness reflects the configured split planes, not local directories.
        ready = http.get("/api/ready")
        assert ready.status_code == 200
        checks = ready.json()["checks"]
        assert checks.get("database") == "ready"
        assert checks.get("object_storage") == "ready"
        assert checks.get("queue") == "ready"

        detail = http.get(f"/api/v1/runs/{run.run_id}")
        assert detail.status_code == 200 and detail.json()["status"] == "succeeded"
        team = http.get(f"/api/v1/runs/{run.run_id}/summary")
        assert team.status_code == 200 and team.json()["total_tracks"] > 0
        artifacts = http.get(f"/api/v1/runs/{run.run_id}/artifacts").json()["artifacts"]
        assert artifacts and all(item["integrity_state"] == "verified" for item in artifacts)


def test_retry_preserves_attempt_chain_across_planes(split):
    coordinator, executor, _settings = split

    first = _ingest(coordinator, profile="test_fail")
    job = coordinator.queue.claim("e2e-worker")
    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.FAILED

    retry = coordinator.retry(first.run_id)
    assert retry.run_id != first.run_id
    assert retry.logical_analysis_id == first.logical_analysis_id
    assert retry.attempt_number == 2
    assert retry.previous_attempt_run_id == first.run_id

    # Attempt 1 stays immutable and failed.
    attempt_one = coordinator.repository.load(first.run_id)
    assert attempt_one.status is AnalysisRunStatus.FAILED and attempt_one.attempt_number == 1

    # copy_input reused the source into the new run's object-storage namespace.
    assert coordinator.object_storage.has_input(retry.run_id) is True

    # test_fail only fails attempt 1, so attempt 2 completes -- with its own bytes.
    job_two = coordinator.queue.claim("e2e-worker")
    assert job_two is not None and job_two.run_id == retry.run_id
    assert executor.execute(job_two, "e2e-worker") is AnalysisRunStatus.SUCCEEDED
    assert coordinator.repository.load(retry.run_id).artifacts


def test_queued_cancellation_prevents_execution(split):
    coordinator, executor, _settings = split

    run = _ingest(coordinator)
    # A cancellation recorded in the repository while still queued must stop the
    # worker from ever running inference; the queue delivery still drains.
    coordinator.repository.request_cancellation(run.run_id)
    job = coordinator.queue.claim("e2e-worker")
    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.CANCELLED

    cancelled = coordinator.repository.load(run.run_id)
    assert cancelled.status is AnalysisRunStatus.CANCELLED
    assert cancelled.artifacts == ()


def test_running_cancellation_stops_at_safe_checkpoint(split):
    coordinator, executor, _settings = split

    run = _ingest(coordinator)
    job = coordinator.queue.claim("e2e-worker")
    # Deterministically place the run in RUNNING, then request cancellation before
    # execution so the first safe checkpoint observes it -- no timing race.
    running = coordinator.repository.load(run.run_id)
    coordinator.repository.save(running.start(stages=running.stages))
    coordinator.repository.request_cancellation(run.run_id)

    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.CANCELLED
    assert coordinator.repository.load(run.run_id).status is AnalysisRunStatus.CANCELLED


def test_deterministic_failure_persists_safe_error_and_allows_retry(split):
    coordinator, executor, _settings = split

    run = _ingest(coordinator, profile="test_fail")
    job = coordinator.queue.claim("e2e-worker")
    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.FAILED

    failed = coordinator.repository.load(run.run_id)
    assert failed.status is AnalysisRunStatus.FAILED
    assert failed.failure is not None and failed.failure.error_code == "test_stage_failure"
    # No partial/unpublished artifacts were registered on a failed attempt.
    assert failed.artifacts == ()
    # Retry remains allowed from a failed attempt.
    assert coordinator.retry(run.run_id).attempt_number == 2


def test_duplicate_delivery_does_not_re_execute(split):
    coordinator, executor, _settings = split

    run = _ingest(coordinator)
    job = coordinator.queue.claim("e2e-worker")
    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.SUCCEEDED
    first = coordinator.repository.load(run.run_id)

    # At-least-once redelivery of the same terminal job must be a no-op: the
    # repository, not the queue, decides the run is already done.
    assert executor.execute(job, "e2e-worker") is AnalysisRunStatus.SUCCEEDED
    second = coordinator.repository.load(run.run_id)
    assert len(second.artifacts) == len(first.artifacts)
    assert second.completed_at == first.completed_at
